SEARCH_DIR(C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\lcl\units\arm-android\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\packager\units\arm-android\)
SEARCH_DIR(C:\LProjects\laztoapk\trunk\bin\TemplateProject\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\httpd22\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\zlib\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\unzip\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\tcl\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\symbolic\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\sqlite\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl-unicode\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl-objpas\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl-extra\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl-console\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\regexpr\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\postgres\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pcap\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\oracle\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\openssl\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\odbc\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\numlib\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\mysql\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\libtar\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\libpng\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\libgd\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\jni\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\imagemagick\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\ibase\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\httpd24\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\hermes\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\hash\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\gdbm\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fppkg\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fpmkunit\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fftw\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-xml\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-stl\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-sound\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-sdo\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-res\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-registry\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-process\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-passrc\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-net\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-json\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-js\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-fpcunit\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-extra\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-db\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-base\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-async\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fastcgi\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\dblib\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\chm\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\bzip2\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\fpc\3.1.1\units\arm-android\rtl\)
SEARCH_DIR(C:\laztoapk\downloads\laz4android\fpc\3.1.1\bin\i386-win32\)
VERSION
{
  {
    global:
      JNI_OnUnload;
      JNI_OnLoad;
      Java_com_pascal_lcltest_LCLActivity_LCLOnMenuAction;
      Java_com_pascal_lcltest_LCLActivity_LCLOnSensorChanged;
      Java_com_pascal_lcltest_LCLActivity_LCLOnConfigurationChanged;
      Java_com_pascal_lcltest_LCLActivity_LCLOnTimer;
      Java_com_pascal_lcltest_LCLActivity_LCLOnKey;
      Java_com_pascal_lcltest_LCLActivity_LCLOnMessageBoxFinished;
      Java_com_pascal_lcltest_LCLActivity_LCLOnCreate;
      Java_com_pascal_lcltest_LCLActivity_LCLDrawToBitmap;
      Java_com_pascal_lcltest_LCLActivity_LCLOnTouch;
    local:
      *;
  };
}
INPUT(
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\dllprt0.o
crtbegin_so.o
c:\LProjects\laztoapk\trunk\bin\TemplateProject\lib\arm-android\templateandroid.o
c:\LProjects\laztoapk\trunk\bin\TemplateProject\lib\arm-android\templateandroid.or
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\system.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\fpintres.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\objpas.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnint.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\interfaces.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\forms.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn_android.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawndrawers.o
c:\LProjects\laztoapk\trunk\bin\TemplateProject\lib\arm-android\templatemain.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\types.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\classes.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\sysutils.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\math.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpimage.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpcanvas.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpimgcanv.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\ctypes.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl-objpas\dateutils.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-xml\xmlread.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-xml\dom.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawn_androidproc.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\jni.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\bitmap.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\log.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\keycodes.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\fileutil.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazutf8.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnproc.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn_common.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawncontrols.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lazcanvas.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lazregions.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lazdeviceapis.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\interfacebase.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\controls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lclproc.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\intfgraphics.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\graphtype.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lcltype.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lmessages.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\graphics.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lclstrconsts.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\menus.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazloggerbase.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\typinfo.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\rtlconsts.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\unix.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\errors.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\sysconst.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\unixtype.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\baseunix.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\unixutil.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\clipping.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fppixlcanv.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\pixtools.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\ellipses.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-xml\xmlutils.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-xml\xmlreader.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-xml\xmltextreader.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-xml\dtdmodel.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-base\uriparser.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lclmessageglue.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wscontrols.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpreadbmp.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpwritebmp.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\bmpcomn.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\fpcadds.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\avglvltree.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lclversion.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpreadpng.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpwritepng.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpreadtiff.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpwritetiff.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fptiffcmn.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\icnstypes.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpimgcmn.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazlogger.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsreferences.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazmethodlist.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazutf8classes.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazclasses.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-base\gettext.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\masks.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazfileutils.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-base\contnrs.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazutilsstrconsts.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\pngcomn.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\zstream.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\zbase.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\gzio.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\hash\crc.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\zdeflate.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\zinflate.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\trees.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\adler.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\infblock.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\infutil.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\infcodes.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\inftrees.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\paszlib\inffast.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lclintf.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpreadpnm.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpwritepnm.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpreadjpeg.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpwritejpeg.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-image\fpreadgif.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lresources.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lclrescache.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\graphmath.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jpeglib.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdapimin.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdatasrc.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdapistd.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jmorecfg.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdeferr.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jinclude.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jerror.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jmemmgr.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdmarker.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdinput.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcomapi.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jutils.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jmemnobs.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdmaster.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdcolor.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdsample.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdpostct.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jddctmgr.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdphuff.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdhuff.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdcoefct.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdmainct.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jquant1.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jquant2.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdmerge.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdct.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jidctfst.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jidctint.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jidctflt.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jidctred.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcapistd.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcapimin.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jdatadst.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcparam.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcinit.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcmarker.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcphuff.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jchuff.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcmaster.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jccolor.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcsample.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcprepct.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcdctmgr.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jccoefct.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jcmainct.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jfdctint.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jfdctfst.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\pasjpeg\jfdctflt.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\dynqueue.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazconfigstorage.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-base\syncobjs.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\utf8process.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\maps.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\lazutf8sysutils.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\themes.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\tmschema.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-process\process.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-process\pipes.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\termio.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\imglist.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\propertystorage.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\actnlist.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\lclclasses.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wslclclasses.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsimglist.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsproc.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsfactory.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-base\rttiutils.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl-objpas\strutils.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsmenus.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customtimer.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\clipbrd.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\fcl-base\custapp.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\helpintfs.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsforms.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\messages.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\stdctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\extctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\comctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\toolwin.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\buttons.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\extendedstrings.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\textstrings.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsstdctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\popupnotifier.o
C:\laztoapk\downloads\laz4android\\fpc\3.1.1\units\arm-android\rtl\fgl.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsextctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\imagelistcache.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsbuttons.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wscomctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wstoolwin.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wslazdeviceapis.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwsfactory.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwsforms.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnprivate.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\calendar.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\spin.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\dialogs.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wscalendar.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsspin.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\buttonpanel.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\wsdialogs.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwsbuttons.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwscomctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwscontrols.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwsextctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwsmenus.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwsspin.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwsstdctrls.o
C:\laztoapk\downloads\laz4android\lcl\units\arm-android\customdrawn\customdrawnwslazdeviceapis.o
C:\laztoapk\downloads\laz4android\components\lazutils\lib\arm-android\paswstring.o
)
INPUT(
-ljnigraphics
-llog
-lc
)
GROUP(
-lc
)
INPUT(
crtend_so.o
)
SECTIONS
{
  .data           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
}
INSERT BEFORE .data1
